### ISSUE TITLE
Web Activities: XML file not processed with latest version of WebActivities activity

### ISSUE THREAD

**Issue by cosminsand** [UiPath/Web.Activities#4]
Attached WF will return results in CSV file using UiPath.Web.Activities version 1.0.6018.14223, but it will not return results when using 1.0.6171.33535
To execute modify the arguments to local path where WF is extracted
![image](https://cloud.githubusercontent.com/assets/16915597/22017596/a56188e8-dcb3-11e6-8eac-a861ed285b6b.png)
[LATAM.zip](https://github.com/UiPath/Activities/files/710750/LATAM.zip)
[UiPath.WebAPI.Activities.1.0.6018.14223.zip](https://github.com/UiPath/Activities/files/710751/UiPath.WebAPI.Activities.1.0.6018.14223.zip)

**Comment by LaviniaC** [comment]
fix with 76fda0d964f51c22c289786e0ca90f8d2b7a9418
